const JWT_EXPIRES_IN = '4h';
const DUPLICATE_KEY_ERROR = 11000;
const SERVER_ERROR_CODES = {
  DUPLICATE_RECORD: "DS-001",
};

module.exports = {
  JWT_EXPIRES_IN,
  DUPLICATE_KEY_ERROR,
  SERVER_ERROR_CODES,
};